### ISSUE TITLE
SIP: Call updateDealState

### ISSUE THREAD

**Issue by kingflurkel** [swarmcity/sc-protocol-docs#12]
## <a name="updateDealState"></a> updateDealState 

Process a chatmsg 
### Data format

**createChatmsg:**

```
/**
 * @request
 * Represents the updateDealState request
 * @param {string} itemId - The name of the msg sender
 * @param {string} operation - The image of the msg sender
 * @param {string} signedtx - The description of the chatmessage
 */

{
	itemId: <String>,
	operation: <String>,
	signedtx: <String>,
}

```

**Returns:**

```
/**
 * Represents the chatmsg response
 * @response
 * @param {number} response - The HTTP response code
 * @param {string} txhash - The txhash / receipt
 */
 
{ 
	response: <Number>,
	txhash: <String>  
}
```

---

### Client
```
// Insert Sponnet's unit test function
```

### Worker
```
// Insert Sponnet's unit test function
subscribe to topic / get blocks in / ...
```

**Comment by kingflurkel** [comment]
Depending on the _opcode_ and the msg.sender, this call executes an update on the deal object. It changes the status. 

Statussess:
- Created
- Funded
- In progress
- Conflict
- Resolved 
- Done

Expects:
- Opcode
- Signed transaction

Returns:
- Success 
- TxHash

Status change triggers update event on Deals subscription

**Comment by sophiii** [comment]
Perhaps this should be implemented with https://github.com/swarmcity/sc-protocol-docs/issues/17

**Comment by kingflurkel** [comment]
@sophiii +1

**Comment by sophiii** [comment]
@kingflurkel can you close in favor of https://github.com/swarmcity/sc-protocol-docs/issues/17
