### ISSUE TITLE
SIP: Call getHashtagList

### ISSUE THREAD

**Issue by kingflurkel** [swarmcity/sc-protocol-docs#4]
## <a name="getHashtagList"></a>getHashtagList

Returns the list of hashtags interesting for the user, based on geolocation.

Call:

```
/**
 * Represents the hashtags request
 * @request
 * @param {boolean} success - If the request was successful or not
 * @param {string} geohash - The user's geolocation. When not available, return worldwide
 */
{
	geohash: <String>,
	// Time range?	
}
```

Returns:

```
/**
 * Represents the list of hashtags
 * @response
 * @param {boolean} success - If the request was successful or not
 * @param {string} contractAddress - The address of the hashtag 
 * @param {string} hashtagName - The hashtag name 
 * @param {string} hashtagBalance - The SWR balance in in wei or smallest erc20 denomination
 * @param {number} children - The number of hashtag children / on chain
 */
{ 
	contractAddress: <String> {
		hashtagName: <String>, 
		hashtagBalance: <String>,
		children: <Number>
	},
       ...
}
```

**Comment by bkawk** [comment]
if the user does not give access to their geohash, this call cant be made, what should we show to the front end?

**Comment by kingflurkel** [comment]
_Worldwide_ with disabled range filter?

**Comment by bkawk** [comment]
if the user does not give access to their location and we want a list of hashtags returning would we post something like....
```
{
	geohash: '0000000000',
}
```

**Comment by kingflurkel** [comment]
When we don't have the geolocation, we use only the first character, meaning "worldwide". 
_My reasoning is that later on in eg. #needaride storefront, the user can drag the map to anywhere in the world and see the activity. This could be great to show how certain cities do things, so others can be inspired by it._

**Comment by bkawk** [comment]
Out of all the first letters which one is to be used for world wide? Please could you give an example?
http://geohash.gofreerange.com/

<img width="629" alt="screen shot 2017-10-02 at 9 47 31 pm" src="https://user-images.githubusercontent.com/14357697/31098690-62985298-a7bb-11e7-8ada-e22d7b6a3981.png">

**Comment by kingflurkel** [comment]
![image](https://user-images.githubusercontent.com/2879379/31098831-470d1802-a7c4-11e7-8b2e-771fc1b27f4b.png)

You're right, I should have looked better :)

**Comment by bkawk** [comment]
I propose `key` is renamed to contractAddress

**Comment by bkawk** [comment]
I propose `children` is further defined as it stands now I don't know what to expect back

**Comment by bkawk** [comment]
I propose an event is added for when any of the data is changed

**Comment by bkawk** [comment]
I propose `success` be renamed to `status` and HTTP status codes used

**Comment by bkawk** [comment]
I propose each response also includes a response time that shows how long it took to execute in milliseconds

**Comment by bkawk** [comment]
I propose we make an example for each api call that not only shows the data format but also shows how to call the function and how to get its values back.
