### ISSUE TITLE
SIP: Call getChildren

### ISSUE THREAD

**Issue by kingflurkel** [swarmcity/sc-protocol-docs#5]
## <a name="getChildren"></a>getChildren

Call:

```
{
	args: {
		filter: {
			user: <String>,                  // 0x...
			hashtag: <String>,            // 0x...
			geolocation: <String>,
			timeRange: { 
				from: <DateTime>, 
				to: <DateTime> 
			}
		}
	}	
}
```

Returns:

```
{ 
	'0x...': {
		Data
	},
	'0x...': {
		Data
	},
	'0x...': {
		Data
	}
}
```

**Comment by bkawk** [comment]
what value does the user key represent?

**Comment by bkawk** [comment]
I propose we rename timerange to timeRange

**Comment by bkawk** [comment]
`args` and `filter` are not both required as `args` only takes a `filter`, I propose `args` is removed

**Comment by bkawk** [comment]
I propose `Data` is renamed to `data`

**Comment by bkawk** [comment]
It is not clear what can be expected in the data object, I propose we detail its contents

**Comment by bkawk** [comment]
it's not clear what children are, can we include a description of what a hashtags child is?

**Comment by bkawk** [comment]
I propose we include `status` that represents an HTTP status code

**Comment by bkawk** [comment]
I propose each response also includes a response time that shows how long it took to execute in milliseconds

**Comment by bkawk** [comment]
I propose an event is added for when any of the data is changed

**Comment by bkawk** [comment]
I propose we make an example for each api call that not only shows the data format but also shows how to call the function and how to get its values back.
