### ISSUE TITLE
SIP: Call getUserRep 

### ISSUE THREAD

**Issue by kingflurkel** [swarmcity/sc-protocol-docs#7]
## <a name="getUserRep"></a>getUserRep

Call:

```
{
	pubkey: <String>		// 0x...	
}
```

Returns:

```
{ 
	'0x...': {
		SWR: <String>, 	// 'NeedARide'
		Balance: <Number>  // smallest denomination (1e18)
	},
	'0x...': {
		SWR: <String>, 	// 'NeedToShop'
		Balance: <Number>  // smallest denomination (1e18)
	},
	'0x...': {
		SWR: <String>, 	// 'SwarmBnB'
		Balance: <Number>  // smallest denomination (1e18)
	}
}
```

**Comment by bkawk** [comment]
I propose this is to be combined with the getHashtagList call https://github.com/swarmcity/sc-protocol-docs/issues/4

**Comment by kingflurkel** [comment]
This one is for a different user than yourself, like when you want to check out the rep of someone responding to your request. But still in the worker it could be combined / we first get hashtaglist then check the balances for that pub key.
